pipeline 
{

agent {
  label 'server1'
}

tools {
  maven 'mymaven'
}

environment {
  NAME = "moninderr"
}


parameters {
  string defaultValue: 'singh', name: 'LASTNAME'
}

stages{

    stage('build'){
        steps {
            sh 'mvn clean package'
            echo "hello $NAME ${params.LASTNAME}"
        }

        

    }

    stage('test')
    {
      parallel {
        stage('testA')
        {
          steps{
            echo "this is test A"
          }
        }
        stage('testB')
        {
          steps{
            echo "this is testB"
          }
        }
      }
      post {
        success {
            archiveArtifacts artifacts: '**/target/*.jar'
                    }
        }
    }

    
}

}